apiVersion: apps/v1
kind: Deployment

metadata:
  name: carts
  namespace: sock-shop
  labels:
    app: carts

spec:
  replicas: 1

  selector:
    matchLabels:
      app: carts

  template:
    metadata:
      labels:
        app: carts

    spec:
      containers:
        - name: carts
          image: weaveworksdemos/carts:0.4.8

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JAVA_OPTS

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE

      volumes:
        - name: tmp-volume
          emptyDir: {}