apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: habiba-dev
  labels:
    app: user

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user

  template:
    metadata:
      labels:
        app: user

    spec:
      containers:
        - name: user
          image: weaveworksdemos/user:0.4.4

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_DB_HOST

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE