apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: sock-shop
  labels:
    app: payment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment

  template:
    metadata:
      labels:
        app: payment

    spec:
      containers:
        - name: payment
          image: weaveworksdemos/payment:0.4.3

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE