apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: catalogue-db
  namespace: habiba-dev

spec:
  serviceName: catalogue-db

  replicas: 1

  selector:
    matchLabels:
      app: catalogue-db

  template:
    metadata:
      labels:
        app: catalogue-db

    spec:
      containers:
        - name: catalogue-db

          image: weaveworksdemos/catalogue-db:0.3.0

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: socksdb

          volumeMounts:
            - name: catalogue-db-storage
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: catalogue-db-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
