apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: sock-shop
  labels:
    app: catalogue
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
