apiVersion: v1
kind: Service

metadata:
  name: orders-db
  namespace: sock-shop

  labels:
    app: orders-db

spec:
  type: ClusterIP

  selector:
    app: orders-db

  ports:
    - port: 27017
      targetPort: 27017
