apiVersion: v1
kind: Service

metadata:
  name: orders
  namespace: habiba-dev

  labels:
    app: orders

spec:
  type: ClusterIP

  selector:
    app: orders

  ports:
    - port: 80
      targetPort: 80
